services:
db:
  container_name: pg_container
  image: postgres
  restart: always
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: slash
    POSTGRES_DB: postgres
  ports:
    - "5432:5432"
  volumes:
    - $HOME/Desktop/PostgreSql-Snippets/infile:/infile
    - pg_data:/var/lib/postgresql/data/
volumes:
  pg_data: